version: '3.7'
services:
    {{cookiecutter.package_name}}_postgres:
        container_name: {{cookiecutter.package_name}}_postgres
        image: postgres:11.9
        environment:
          - POSTGRES_USER={{cookiecutter.package_name}}
          - POSTGRES_PASSWORD={{cookiecutter.package_name}}
          - POSTGRES_DB={{cookiecutter.package_name}}
          - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
          - 54321:5432
        volumes:
          - /var/lib/postgresql/data/pgdata
        logging:
            options:
                max-size: 10m
                max-file: "3"
    {{cookiecutter.package_name}}_api:
      container_name: {{cookiecutter.package_name}}_api
      depends_on:
        - {{cookiecutter.package_name}}_postgres
      build:
        context: ../
        dockerfile: Dockerfile
      ports:
        - "5000:5000"
      environment:
        - DATABASE_URL=postgres://{{cookiecutter.package_name}}:{{cookiecutter.package_name}}@{{cookiecutter.package_name}}_postgres/{{cookiecutter.package_name}}
      entrypoint: /app/docker-compose/api-entrypoint.sh
